version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:12.5.0

commands:
  update-npm:
    steps:
      - run: sudo npm install -g npm@latest
  install-npm-wee:
    steps:
      - run: npm ci
  build:
    steps:
      - run: npm run tsc
  deploy-master-to-heroku:
    steps:
      - run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  create-docker-img:
    steps:
      - run: |
          docker build -t epicbulletinboard/bulletinboard:$CIRCLE_SHA1 .
  push-latest-docker-img:
    steps:
      - run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS" 
          docker push epicbulletinboard/bulletinboard:$CIRCLE_SHA1
  deploy-docker-to-heroku:
    steps:
      - run: |
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker tag anssi/bulletinboard:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
  install-docker-client:
    steps:
      - run: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          sudo mv /tmp/docker/* /usr/bin

jobs:
  build:
    working_directory: ~/EPIC-BULLETIN-BOARD-PROJECT
    executor: default
    steps:
      - checkout
      - update-npm
      - install-npm-wee
      - build
  deploy:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - install-docker-client
      - create-docker-img
      - push-latest-docker-img
      - deploy-docker-to-heroku
workflows:
  build-deploy:
    jobs:
      - build
      - deploy
        #filters:
        #branches:
        #only: master
