version: 2.1
jobs:
  build:
    working_directory: ~/EPIC-BULLETIN-BOARD-PROJECT
    docker:
      - image: circleci/node:12.5.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm ci
      - run:
          name: build
          command: npm run tsc
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
