version: 2
jobs:
  build:
    working_directory: ~/EPIC-BULLETIN-BOARD-PROJECT
    docker:
      - image: circleci/node:12.5.0
    steps:
      
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run tsc
      -run:
          name: Deploy Master to Heroku
          command: | git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
