version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:12.5.0

commands:
  update-npm:
    description: 'Install latest npm'
    steps:
      - run: sudo npm install -g npm@latest
  install-npm-wee:
    description: 'install dependencies'
    steps:
      - run: npm ci
  build:
    description: 'Compile typescript code'
    steps:
      - run: npm run tsc
  run-tests:
    description: 'Run tests'
    steps:
      - run: npm run test
  deploy-master-to-heroku:
    description: 'Deploy master to Heroku'
    steps:
      - run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  create-docker-img:
    description: 'Create docker image'
    steps:
      - run: |
          docker build -t epicbulletinboard/bulletinboard:$CIRCLE_SHA1 .
  push-latest-docker-img:
    description: 'Push latest docker image to Dockerhub'
    steps:
      - run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS" 
          docker push epicbulletinboard/bulletinboard:$CIRCLE_SHA1
  deploy-docker-to-heroku:
    description: 'Push and deploy latest docker image to Heroku'
    steps:
      - run: |
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker tag epicbulletinboard/bulletinboard:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME
  install-docker-client:
    description: 'Install Docker client'
    steps:
      - run: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          sudo mv /tmp/docker/* /usr/bin

jobs:
  build:
    working_directory: ~/EPIC-BULLETIN-BOARD-PROJECT
    executor: default
    steps:
      - checkout
      - update-npm
      - install-npm-wee
      - build
  deploy:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - install-docker-client
      - create-docker-img
      - push-latest-docker-img
      - deploy-docker-to-heroku
  test:
    executor: default
    steps:
      - checkout
      - run-tests
workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
