import Index from './routers/Index';
import PostController from './controllers/PostController';
import CategoryController from './controllers/CategoryController';
import Post from './orm/entities/Post';
import { Repository } from 'typeorm';
import Category from './orm/entities/Category';
import ValidationMiddleWare from './middleware/ValidationMiddleware';
import errorMiddleware from './middleware/error.middleware';
import EnvVariables from './dto/EnvVariables';
import PostService from './services/PostService';
import CategoryService from './services/CategoryService';
import User from './orm/entities/User';
import UserService from './services/UserService';
import UserController from './controllers/UserController';

export type Dependencies = {
  index: Index;
  postController: PostController;
  categoryController: CategoryController;
  userController: UserController;
  postRepo: Repository<Post>;
  categoryRepo: Repository<Category>;
  userRepo: Repository<User>;
  errorMiddleware: typeof errorMiddleware;
  envVariables: EnvVariables;
  postService: PostService;
  categoryService: CategoryService;
  userService: UserService;
  validator: ValidationMiddleWare;
};
